language: node_js
node_js:
  - 8
  - 4
script:
  - npm run build-pg-formatter
  - npm run lint
  - npm run test
  # - nyc --silent npm run test
  # - nyc report --reporter=text-lcov | coveralls
  # - nyc check-coverage --lines 90
after_success:
  - npm run build-pg-formatter
  - NODE_ENV=production npm run build
  - semantic-release pre
  - npm publish
  - semantic-release post
notifications:
  email: false
sudo: false
